resolver: lts-8.20
packages:
- '.'
- location:
    git: https://github.com/mrkkrp/megaparsec.git
    commit: 214d1f2c1897bf657f52d83509d672d756b152ad
  extra-dep: true
extra-deps:
- parser-combinators-0.1.0
