resolver: lts-8.19
packages:
- '.'
- location:
    git: https://github.com/mrkkrp/megaparsec.git
    commit: 785d006f02565f4254d6672bade287a829a6f54c
  extra-dep: true
extra-deps:
- parser-combinators-0.1.0
